name: pytest

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  python-matrix:
    name: python-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.x"
    steps:
    # Pixi should manage Python versions, but it doesn't work on Windows in GitHub Actions
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/checkout@v4

    - name: Set up pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: v0.49.0
        environments: dev

    - name: Install project in editable mode
      run: pixi run -e dev install-dev

    - name: Run tests
      run: pixi run -e dev test
